<?php if (DEBUG) { ?>
<script src="<?=v('/42/js/polyfill/polyfill.js')?>"></script>
<script src="<?=v('/42/os/vendor/localforage.js')?>"></script>
<script src="<?=v('/42/os/vendor/FileSaver.js')?>"></script>
<script src="<?=v('/42/os/vendor/howler.js')?>"></script>
<script src="<?=v('/42/js/noop.js')?>"></script>
<script src="<?=v('/42/js/delegate.js')?>"></script>
<script src="<?=v('/42/js/io.js')?>"></script>
<script src="<?=v('/42/js/watch.js')?>"></script>
<script src="<?=v('/42/js/kernel.js')?>"></script>
<script src="<?=v('/42/js/utils.js')?>"></script>
<script src="<?=v('/42/js/selection.js')?>"></script>
<script src="<?=v('/42/js/ajax.js')?>"></script>
<script src="<?=v('/42/js/chain.js')?>"></script>
<script src="<?=v('/42/js/db.js')?>"></script>
<script src="<?=v('/42/js/el.js')?>"></script>
<script src="<?=v('/42/js/on.js')?>"></script>
<script src="<?=v('/42/js/extend.js')?>"></script>
<script src="<?=v('/42/js/undo.js')?>"></script>
<script src="<?=v('/42/js/screenshot.js')?>"></script>
<script src="<?=v('/42/js/socket.js')?>"></script>
<script src="<?=v('/42/js/template.js')?>"></script>
<script src="<?=v('/42/js/archive.js')?>"></script>
<script src="<?=v('/42/js/loop.js')?>"></script>
<script src="<?=v('/42/js/inputs/key.js')?>"></script>
<script src="<?=v('/42/js/inputs/gamepad.js')?>"></script>
<script src="<?=v('/42/js/inputs/wheel.js')?>"></script>
<script src="<?=v('/42/js/ui/cli.js')?>"></script>
<script src="<?=v('/42/js/ui/box.js')?>"></script>
<script src="<?=v('/42/js/ui/drag.js')?>"></script>
<script src="<?=v('/42/js/ui/pos.js')?>"></script>
<script src="<?=v('/42/js/ui/resize.js')?>"></script>
<script src="<?=v('/42/js/ui/notif.js')?>"></script>
<script src="<?=v('/42/js/ui/menu.js')?>"></script>
<script src="<?=v('/42/js/ui/form.js')?>"></script>
<script src="<?=v('/42/os/ui/form.plugins.js')?>"></script>
<script src="<?=v('/42/js/ui/window.js')?>"></script>
<script src="<?=v('/42/js/ui/window.plugins.js')?>"></script>
<script src="<?=v('/42/os/boot/system42.js')?>"></script>
<script src="<?=v('/42/os/boot/boot.js')?>"></script>
<script src="<?=v('/42/os/boot/bios.js')?>"></script>
<script src="<?=v('/42/os/boot/settings.js')?>"></script>
<script src="<?=v('/42/os/boot/storage.js')?>"></script>
<script src="<?=v('/42/os/boot/reset.js')?>"></script>
<script src="<?=v('/42/os/boot/audio.js')?>"></script>
<script src="<?=v('/42/os/boot/splash.js')?>"></script>
<script src="<?=v('/42/os/boot/utils.js')?>"></script>
<script src="<?=v('/42/os/boot/config.js')?>"></script>
<script src="<?=v('/42/os/boot/start.js')?>"></script>
<script src="<?=v('/42/os/boot/register.js')?>"></script>
<script src="<?=v('/42/os/boot/reveal.js')?>"></script>
<script src="<?=v('/42/os/sys/exe.js')?>"></script>
<script src="<?=v('/42/os/sys/fs.js')?>"></script>
<script src="<?=v('/42/os/sys/file.js')?>"></script>
<script src="<?=v('/42/os/sys/explorer.js')?>"></script>
<script src="<?=v('/42/os/sys/explorer.drop.js')?>"></script>
<script src="<?=v('/42/os/sys/editor.js')?>"></script>
<script src="<?=v('/42/js/loader.js')?>"></script>
<?php } else { ?>
<script src="<?=v('/c/sys42.js')?>"></script>
<?php } ?>